name: art_marketplace
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  flutter_native_splash: ^2.2.19
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/artsylane_logo_full.png
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/artsylane_logo_full.png
    - assets/images/artsylane_logo2.png

